title: "Awesome Jailbreaking Academy Resources"
description: "A curated list of high-quality resources for learning and practicing jailbreaking."
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
markdown: kramdown
kramdown:
  auto_ids: true
